export type Language = "en" | "zh";

export const copy = {
  en: {
    eyebrow: "Evidence-based planner",
    subtitle: "A minimal fat-loss planner for calorie deficit, high-protein dieting, and male carb cycling.",
    sex: "Sex",
    male: "Male",
    female: "Female",
    maleChoice: "Training-led setup",
    femaleChoice: "Recovery-aware setup",
    plan: "Plan",
    standard: "Standard",
    carbCycling: "Carb Cycling",
    standardChoice: "Stable daily calories",
    carbChoice: "Carbs around hard sessions",
    carbNote: "Carb cycling keeps the weekly deficit fixed and shifts carbohydrates toward the hardest resistance-training days.",
    bodyData: "Body data",
    age: "Age",
    height: "Height cm",
    weight: "Weight kg",
    target: "Target kg",
    expectedTimeline: "Expected timeline weeks",
    activity: "Activity",
    trainingDays: "Training days",
    weeklyLoss: "Weekly loss %",
    protein: "Protein g/kg",
    saveLocal: "Save plan locally",
    savedLocal: "Saved locally",
    adjustTimeline: "Adjust timeline first",
    result: "Result",
    calories: "Calories",
    proteinShort: "Protein",
    fat: "Fat",
    carbs: "Carbs",
    high: "High Carb Day",
    medium: "Medium Carb Day",
    low: "Low Carb Day",
    weeklyStructure: "Weekly structure",
    highNote: "High-carb days should be assigned to the hardest sessions, not to uncontrolled cheat meals.",
    safety: "Safety notes",
    projection: "Target timeline projection",
    projectionNote: "When a target weight is set, this projection follows your expected timeline. If no target is set, it falls back to 12 weeks.",
    week: "Week",
    projectedWeight: "Projected weight",
    expectedLoss: "Expected loss",
    weeklyCheck: "Weekly calorie check",
    targetWeeklyCalories: "Target weekly calories",
    allocatedWeeklyCalories: "Allocated weekly calories",
    difference: "Difference",
    execution: "Execution rules",
    standardRules: "Keep calories consistent, hit protein daily, use strength training to preserve lean mass, and adjust only after two weeks of 7-day average weight data.",
    carbRules: "Keep weekly calories fixed. Put high-carb days on heavy legs, deadlift, or full-body sessions. Low-carb days are for rest, walking, or light cardio.",
    femaleRules: "Use a moderate deficit, do not overreact to premenstrual water-weight changes, and monitor sleep, recovery, menstrual regularity, and hunger.",
    riskSetTarget: "Set target to assess risk",
    riskSetTargetDetail: "Enter a target weight and timeline to calculate the required weekly loss rate.",
    riskNoLossTarget: "Target is not below current weight",
    riskNoLossTargetDetail: "If the target is not fat loss, the app keeps the default weekly loss setting.",
    riskSafe: "Conservative range",
    riskStandard: "Standard range",
    riskAggressive: "Aggressive range",
    riskHigh: "High-risk range",
    riskBlocked: "Timeline too short",
    riskDetail: "Requires about {loss} kg/week, equal to {rate}% of body weight per week. Standard recommendation: at least {standardWeeks} weeks; hard minimum: no less than {hardWeeks} weeks.",
    buildFirst: "Build your plan first",
    buildFirstDetail: "Start with the essential data. The app will not show default personal numbers before you save a real plan.",
    startSetup: "Start setup",
    setupHeader: "Set your baseline",
    setupSubhead: "Move through one focused step at a time, then review the plan before saving.",
    stepBody: "Body data",
    stepGoal: "Goal weight",
    stepTimeline: "Timeline",
    changeData: "Change data",
    close: "Close",
    status: "Status",
    readyTitle: "Core target",
    readyDetail: "Your saved target for the current plan.",
    readyBadge: "Saved",
    next: "Next",
    back: "Back",
    review: "Review",
    saveAndView: "Save and view plan",
    stepPlanTitle: "Choose your setup",
    stepPlanDetail: "Select the biological setup, plan style, and normal activity level.",
    stepBodyTitle: "Tune the numbers",
    stepBodyDetail: "Adjust the key body data with light sliders or precise steppers.",
    stepReviewTitle: "Review before saving",
    stepReviewDetail: "Confirm the target pace and core outputs before the app builds your dashboard.",
    coreTarget: "Core target",
    planStyle: "Plan style",
    notSet: "Not set"
  },
  zh: {
    eyebrow: "证据导向减脂计划",
    subtitle: "极简科学减脂工具：热量缺口、高蛋白饮食，以及男士训练导向碳水循环。",
    sex: "性别",
    male: "男士",
    female: "女士",
    maleChoice: "训练导向设置",
    femaleChoice: "恢复优先设置",
    plan: "方案",
    standard: "标准减脂",
    carbCycling: "碳水循环",
    standardChoice: "每天热量更稳定",
    carbChoice: "围绕高强度训练分配碳水",
    carbNote: "碳水循环保持每周总赤字不变，只把更多碳水分配给最难的力量训练日。",
    bodyData: "身体数据",
    age: "年龄",
    height: "身高 cm",
    weight: "体重 kg",
    target: "目标体重 kg",
    expectedTimeline: "期待完成用时（周）",
    activity: "活动水平",
    trainingDays: "每周训练天数",
    weeklyLoss: "每周下降 %",
    protein: "蛋白 g/kg",
    saveLocal: "保存到本机",
    savedLocal: "已保存",
    adjustTimeline: "先调整目标时间",
    result: "结果",
    calories: "热量",
    proteinShort: "蛋白质",
    fat: "脂肪",
    carbs: "碳水",
    high: "高碳日",
    medium: "中碳日",
    low: "低碳日",
    weeklyStructure: "一周结构",
    highNote: "高碳日应该给最重的训练日，不是用来失控放纵。",
    safety: "安全提示",
    projection: "目标时间预测",
    projectionNote: "设置目标体重后，预测长度会跟随期待完成用时；未设置目标体重时，默认显示 12 周。",
    week: "周数",
    projectedWeight: "预测体重",
    expectedLoss: "预计下降",
    weeklyCheck: "周热量核验",
    targetWeeklyCalories: "目标周热量",
    allocatedWeeklyCalories: "分配周热量",
    difference: "差值",
    execution: "执行规则",
    standardRules: "保持热量稳定，每天打够蛋白，用力量训练保留瘦体重；至少观察两周 7 日平均体重后再调整。",
    carbRules: "保持周热量不变。高碳日给重腿、硬拉、全身大容量训练；低碳日用于休息、步行或轻有氧。",
    femaleRules: "使用温和赤字，不要因经前水重波动误判失败，并持续观察睡眠、恢复、月经规律和饥饿感。",
    riskSetTarget: "设置目标后评估风险",
    riskSetTargetDetail: "输入目标体重和期待完成用时后，系统会计算所需每周下降速度。",
    riskNoLossTarget: "目标体重不低于当前体重",
    riskNoLossTargetDetail: "如果目标不是减重，系统会使用默认每周下降设置。",
    riskSafe: "保守区间",
    riskStandard: "标准区间",
    riskAggressive: "激进区间",
    riskHigh: "高风险区间",
    riskBlocked: "时间过短，不建议生成计划",
    riskDetail: "需要约 {loss} kg/周，等于当前体重的 {rate}%/周。标准建议至少 {standardWeeks} 周；硬性最低建议不少于 {hardWeeks} 周。",
    buildFirst: "先建立你的计划",
    buildFirstDetail: "先填写关键数据。保存真实计划之前，App 不展示默认个人数字。",
    startSetup: "开始设置",
    setupHeader: "建立基础数据",
    setupSubhead: "一步只处理一个重点，最后确认后再保存计划。",
    stepBody: "身体数据",
    stepGoal: "目标体重",
    stepTimeline: "完成周期",
    changeData: "Change data",
    close: "关闭",
    status: "状态",
    readyTitle: "核心目标",
    readyDetail: "这是当前计划保存后的主要目标。",
    readyBadge: "已保存",
    next: "下一步",
    back: "返回",
    review: "确认",
    saveAndView: "保存并查看计划",
    stepPlanTitle: "选择计划基础",
    stepPlanDetail: "选择身体设置、计划类型和日常活动水平。",
    stepBodyTitle: "微调关键数据",
    stepBodyDetail: "用滑杆和精确微调设置核心身体数据。",
    stepReviewTitle: "保存前确认",
    stepReviewDetail: "确认目标速度和核心输出后，再进入计划首页。",
    coreTarget: "核心目标",
    planStyle: "方案类型",
    notSet: "未设置"
  }
} as const;

export type AppCopy = typeof copy.en | typeof copy.zh;
